### PR TITLE
Add 'dist' task to gruntfile to specify build directory

### PR DESCRIPTION
**Pull request by ajoslin**
Add 'dist' task to gruntfile to specify build directory

### CODE REVIEW

**Comment by ajoslin** [comment]
Does this look good to everyone else?

**Comment by petebacondarwin** [comment]
What happens if you don't specify dist ?

Pete
...from my mobile.

**Comment by ajoslin** [comment]
If you don't specify, it uses the default specified in `initConfig`

**Comment by petebacondarwin** [comment]
I can't see it specified in the initConfig. Perhaps we should add it

**Comment by ajoslin** [comment]
It's easy to miss, it's the first line of initConfig https://github.com/angular-ui/angular-ui/blob/67eed39323f138cab22ef79a6f87df172be57c49/grunt.js#L11

**Comment by ProLoser** [comment]
Looks good to me. Just out of curiosity, what were you doing that lead you to need this (not that I have a problem with it)?

**Comment by ajoslin** [comment]
It's for the build server, to put files in a different folder.

**Pull request merged**
