### PR TITLE
Introduced ui-sortable directive

### PR DESCRIPTION
**Pull request by teamon**
jQuery UI Sortable plugin wrapper

Example: http://jsfiddle.net/7eTMV/20/ or http://plnkr.co/edit/IcYTPU (jsfiddle is hackish)

I need some help with tests - does anyone know how to start testing drag & drop sorting?

### CODE REVIEW

**Comment by ProLoser** [comment]
So my coworker was able to create a draggable directive using the
passthrough directive and the event directive has been proving quite
useful. I have been wondering if it's possible to do sortable using these 2
directives together?

I'm a little confused looking at the organization of your code, what is it
doing to enhance integration with angular? Can you comment some of the code
as the logic is a little... opaque to me.

On Fri, Jul 27, 2012 at 11:12 AM, Tymon Tobolski <
reply@reply.github.com

**Comment by teamon** [comment]
I added some comments. Basically this directive hooks at 'update' callback and reorders item in model.

**Comment by ajoslin** [comment]
Couldn't you just do:

``` html
<div ui-jq="sortable" 
  ui-options="mySortableOptions" 
  ui-event="{'update': 'onUpdate($event)', 'receive': 'onReceive($event)'}">
</div>
```

**Comment by teamon** [comment]
Well, you could take the same approach with date picker, yet there is ui-date in angualr-ui.

**Comment by ProLoser** [comment]
@ajoslin I forgot, what was the issue we ran into when we tried the datepicker on the improved passthrough?

**Comment by ajoslin** [comment]
@teamon, well..you have a point :-).  The reason ui-date is a directive really is [this line](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/date/date.coffee#L33).  With the recent changes to ui-jq, the only hard part now is ng-model change -> directive change.

The reasons this could be its own directive are [line 26](https://github.com/angular-ui/angular-ui/pull/119/files#L1R26) and [line 18](https://github.com/angular-ui/angular-ui/pull/119/files#L1R18).

If we could think of a generic way to do this kinda stuff, it would be cool...

**Comment by ProLoser** [comment]
@teamon don't interpret this discussion as negative in any way. Honestly I think we are constantly trying ways to kill off our own directives with more versatile general-purpose directives, otherwise we could easily get caught up developing a new directive for each and every plugin out there.

With that said, I think it would be good to implement this directive.

**Comment by ajoslin** [comment]
I think it would be cool to implement it without the onStart and onUpdate options - people can use ui-event or ui-options for those.  This could be a really minimal directive

**Comment by ProLoser** [comment]
What would it do then if those 2 were left out?

On Fri, Jul 27, 2012 at 2:30 PM, Andy Joslin <
reply@reply.github.com

**Comment by teamon** [comment]
@ProLoser - Don't worry, I don't :) I agree that there should be some general solution. In case of sortable onStart and onUpdate are needed to find out what has changed in the DOM. The other way (notifying DOM about model change) happens ootb in angular.

**Comment by ajoslin** [comment]
Sorry, I mean not having opts.start and opts.update.  People should be pointed to using ui-event or ui-options for these (and the rest of the possible events for ui-sortable), instead of the directive having to handle all of 'em

**Comment by ProLoser** [comment]
If the original plugin takes those as options they should also be
supported, no?

On Fri, Jul 27, 2012 at 2:41 PM, Andy Joslin <
reply@reply.github.com

**Comment by ajoslin** [comment]
http://jqueryui.com/demos/sortable/

Ya, and you can pass them in with ui-options, and in your $scope declare an update function. Eg:

``` javascript
$scope.myOptions = { update: $scope.updateFn }
```

``` html
<div ui-sortable ui-options="myOptions"></div>
```

There are about 15 events that are passed to the element, too, which ui-event can catch.

**Comment by teamon** [comment]
@ajoslin How to "merge" sortable callback (those provided by user and those provided by directive that are required to make the binding work)?

**Comment by ajoslin** [comment]
I guess you would have to compose it.

``` javascript
var options = attrs.uiOptions || {};
function directiveUpdateFn() { ..your current code.. };

if (options.update) {
  var _update = options.update;
  options.update = function(args) {
    _update(args);
    directiveUpdateFn(args)
  }
}
```

But in your directive, I would recommend using $(elm).bind('update') instead of the option, so the users are free to.

**Comment by teamon** [comment]
Ok, I tried with bind("startupdate", function() {.. }) here http://plnkr.co/edit/IcYTPU

There is an issue. Since directive "startupdate" callback and user provided "update" callback are run simultaneously there is indeterministic value of $scope.items (sometimes before drag, sometimes after, sometimes in the middle etc) - not so good.

**Comment by ajoslin** [comment]
I guess you'll have to compose it, then.  It won't end up being far from your original, lol :)

Would you mind adding basic unit tests, too?  There are lots of examples in the other directives.

**Comment by ProLoser** [comment]
I totally need this directive now lol. I have a specific use-case it would help me with.

**Comment by teamon** [comment]
Updated code and example: http://plnkr.co/edit/IcYTPU

I'm working on tests now

**Comment by teamon** [comment]
I've added some specs (really dumb one actually). As stated in comment I can't figure out how to correctly trigger "update" callback so that ng-model could get updated. Any ideas?

**Comment by ajoslin** [comment]
What does the 'ui' object look like?  You could console.log it and create a mock version.

**Comment by abdulazeezsk** [comment]
Hi, change() function is not being fired after the sorting, here is the plunker for the same, http://plnkr.co/edit/PrJNaw?p=preview

Am i missing anything here? Kindly help.

**Comment by teamon** [comment]
`opts.update` is empty, but I'm not sure why

**Comment by abdulazeezsk** [comment]
Looks like scope.$eval is not evaluating in case of isolated scope.

Have posted this on angular group, will update if i get any replies. This would be applicable to all directives(using ui-options) 

Scope.$eval is not evaluating function definition in the case of isolated scope.

http://plnkr.co/edit/PrJNaw?p=preview

Usecase:
Directive(ui-sortable) works fine when it is used directly inside a template. It fires update event once the sorting is completed. http://plnkr.co/edit/xMhQKw?p=preview
Directive(ui-sortable) works fine when it is used directly inside a directive. However, it doesn't fire any event after the sorting. Reason for that is scope.$eval doesn't evaluate the function that is passed as options to ui-sortable directive in case of isolated scope. Here is the plunker for the same, http://plnkr.co/edit/PrJNaw?p=preview

**Comment by Letsan** [comment]
ui-sortable should be added to the docs (no sign of it in http://angular-ui.github.com/).

Most people will indeed use the jQuery passthrough to implement this if they don't know it's there

**Comment by ghost** [comment]
@Letsan :+1:

**Pull request merged**
