### PR TITLE
Travis-CI

### PR DESCRIPTION
**Pull request by ProLoser**
Unfortunately Travis only supports Firefox, but it's better than nothing (for now).

@pkozlowski-opensource is this branch working? Can we just merge it in so we can (finally) start getting build tests?

Also, why is the `ui-input` in this branch?

I think we need to change the tests folder in the config from keypress back to everything

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Should fix #188

**Comment by pkozlowski-opensource** [comment]
@ProLoser Woops, ui-input should not be here, this is my mistake (!).

I wouldn't merge it in this state as I was experimenting with multiple testacular versions. What I would propose is to close this PR and I would prepare a new, clean one (of the current master, with the latest testacular etc.). 

Still, the major problem is that tests are failing on Travis-CI if all the test are included (!). Please check my comments:
- https://github.com/angular-ui/angular-ui/issues/188#issuecomment-8406243
- https://github.com/angular-ui/angular-ui/issues/188#issuecomment-8402971

If no one objects I will close this PR and will open a fresh, clean one. Then we can try to figure out why tests are failing if run in a certain combination.

**Comment by ProLoser** [comment]
I think you're free to take over the Travis PRs since you're the only one
spearheading them. Do whatever you need.

My only objection, which is only at merge time, is not to disable even
tests. I don't mind having tests fail, but I don't want us to forget to
re-enable tests in the core/master.

On Fri, Sep 21, 2012 at 4:53 PM, Pawel Kozlowski
notifications@github.comwrote:

> @ProLoser https://github.com/ProLoser Woops, ui-input should not be
> here, this is my mistake (!).
> 
> I wouldn't merge it in this state as I was experimenting with multiple
> testacular versions. What I would propose is to close this PR and I would
> prepare a new, clean one (of the current master, with the latest testacular
> etc.).
> 
> Still, the major problem is that tests are failing on Travis-CI if all the
> test are included (!). Please check my comments:
> - angular-ui/angular-ui#188https://github.com/angular-ui/angular-ui/issues/188#issuecomment-8406243
> - angular-ui/angular-ui#188https://github.com/angular-ui/angular-ui/issues/188#issuecomment-8402971
> 
> If no one objects I will close this PR and will open a fresh, clean one.
> Then we can try to figure out why tests are failing if run in a certain
> combination.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/pull/205#issuecomment-8783469.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by boneskull** [comment]
I'll try to help with figuring out why tests are failing.  Usually it's just a test that didn't clean up after itself properly.

**Comment by pkozlowski-opensource** [comment]
Closing this PR. I will prepare a fresh one, starting off the master, with one commit only, without ui-input etc.

**Pull request closed without merging**
