### PR TITLE
fix(mask): mask can now work with original jquery.maskedinput plugin

### PR DESCRIPTION
**Pull request by just-boris**
I move mask value validation into the directive and update jquery.maskedinput plugin to lastest version. Plugin now compatible with jquery 1.9.
Furthermore I add test of optional part of mask, because it is important part of my changes

### CODE REVIEW

**Comment by ProLoser** [comment]
Can you go through this list: https://github.com/angular-ui/angular-ui/blob/master/CONTRIBUTING.md

**Comment by just-boris** [comment]
Sorry for first commit, now that looks better

**Comment by just-boris** [comment]
I found issue in Opera in this fix. I need make some changes before committing it again

**Comment by just-boris** [comment]
Sometimes the value is set from element.val(). Now parser always gets value from maskedinput directly and ignores other values.
Moreover, current master has the error: http://screencast.com/t/yBGSgfFcL0ip (Opera 12.14, IE9)
After this fix it works normal

**Comment by shaungrady** [comment]
uiMask has since been refactored, this issue is no long applicable. It will be in the next AngularUI release. jQuery dependency has been removed.

**Pull request closed without merging**
