### PR TITLE
added equalsTracker and a unit test for #427

### PR DESCRIPTION
**Pull request by joshkurz**
equalsTracker was not added into 0.4.0, but the calendar still looks for it. 

added equalsTracker var
added a unit test for the new feature

http://jsfiddle.net/joshkurz/pDbsH/8/

### CODE REVIEW

**Comment by ggayan** [comment]
is this change going to be released soon?

cheers

**Comment by ProLoser** [comment]
@ggayan yeah I'll try to fast-track this one, but I may have to do it all in v0.4.1

**Comment by ggayan** [comment]
Thanks, I'm just developing a new feature for my company using the calendar and got this issue when updated angular-ui to 0.4.0. I'm applying the fix manually for the moment :)

Thanks!

**Comment by ProLoser** [comment]
@ggayan if you give me the okay that this fixes things I'll merge it in. Unfortunately I feel lame rewriting the git history so this will have to go in a version bump.

**Comment by ggayan** [comment]
Yup, this fixes the issue.

:+1:

**Comment by sgentile** [comment]
what do I need to do to apply this - I'm getting calendars errors as well (so is the github site)!

**Comment by ProLoser** [comment]
@sgentile pull the latest from master and build locally. Or just copy-paste this into your copy of AngularUI and replace the original: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/calendar/calendar.js

**Comment by sgentile** [comment]
Awesome, thanks for the quick response!

**Comment by sgentile** [comment]
@ProLoser Dean, I'm not seeing any events on the calendar - I've literally used the same example on the github site, with this change.  I'm not getting errors - but not seeing any events as well

**Comment by joshkurz** [comment]
are you sure that you are passing in the eventSources object into the
calendar rather than a single event source? Also if you are trying to
replicate the same example on the demo site then you should include the
gCal.js source at the top or else you will get xhr errors. I am going to
update the demo even more now that the head is aligned correctly.

On Thu, Feb 14, 2013 at 6:18 PM, Steve Gentile notifications@github.comwrote:

> @ProLoser https://github.com/ProLoser Dean, I'm not seeing any events
> on the calendar - I've literally used the same example on the github site,
> with this change. I'm not getting errors - but not seeing any events as well
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/pull/428#issuecomment-13584518.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by sgentile** [comment]
Hmm, I'm doing like the demo - I will wait for you to update it then I'll take a look

I'm using:

$scope.events = [
        { title: 'All Day Event', start: new Date(y, m, 1) },
        { title: 'Long Event', start: new Date(y, m, d - 5), end: new Date(y, m, d - 2) },
        { id: 999, title: 'Repeating Event', start: new Date(y, m, d - 3, 16, 0), allDay: false },
        { id: 999, title: 'Repeating Event', start: new Date(y, m, d + 4, 16, 0), allDay: false },
        { title: 'Birthday Party', start: new Date(y, m, d + 1, 19, 0), end: new Date(y, m, d + 1, 22, 30), allDay: false },
        { title: 'Click for Google', start: new Date(y, m, 28), end: new Date(y, m, 29), url: 'http://google.com/' }
    ];

with 

<div ui-calendar="{height: 450,editable: true}" class="span8 calendar" ng-model="events"></div>

**Comment by sgentile** [comment]
I figured it out :

$scope.events = [
        { title: 'All Day Event', start: new Date(y, m, 1) },
        { title: 'Long Event', start: new Date(y, m, d - 5), end: new Date(y, m, d - 2) },
        { id: 999, title: 'Repeating Event', start: new Date(y, m, d - 3, 16, 0), allDay: false },
        { id: 999, title: 'Repeating Event', start: new Date(y, m, d + 4, 16, 0), allDay: false },
        { title: 'Birthday Party', start: new Date(y, m, d + 1, 19, 0), end: new Date(y, m, d + 1, 22, 30), allDay: false },
        { title: 'Click for Google', start: new Date(y, m, 28), end: new Date(y, m, 29), url: 'http://google.com/' }
    ];

```
$scope.eventSources = [$scope.events];
```

ui-calendar="{height: 450,editable: true}" class="span8 calendar" ng-model="eventSources"

**Comment by joshkurz** [comment]
ok cool. Ill update the demo to show off more functionality the new calendar offers in the next day or two. 
Adding eventSources, filtering eventSources (even if the filtered source has the same length as the prior event source), adding events to any source the calendar is using, and calling native calendar methods from the scope.

**Comment by sgentile** [comment]
great, thanks for you work on this - I really like what you have done here!

**Comment by joshkurz** [comment]
np glad you like it.

On Thu, Feb 14, 2013 at 10:35 PM, Steve Gentile notifications@github.comwrote:

> great, thanks for you work on this - I really like what you have done here!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/pull/428#issuecomment-13591537.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Pull request merged**
