### PR TITLE
reformatted all code to use 2 spaces for tabs.  moved bootstrap code lib...

### PR DESCRIPTION
**Pull request by boneskull**
... out of modalSpec.js because it's ugly as sin.

Assuming we wanted to do this, I went ahead and did it.  I also corrected a couple places in the code where we didn't need semicolons.  Also some other slight formatting changes happened like a space after the word "function".  I can redo this if people hate that, but I like it.

All tests pass, so I think this should be OK.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
OK, just pulled the f5c9f2d into my master and there are number of things:
- on the positive side, lint is complaining far less
- could you reformat the common/ieshiv/ieshiv.js as well? lint is still upset about this one (mixed tabs / spaces)

The worst thing is that now I've got failing tests for the 'modal' directive (chrome):

Chrome 21.0 modal model change should open modal FAILED
        TypeError: Object [object Object] has no method 'modal'
            at Object.link [as fn](D:/work/gitrepos/angular-ui/angular-ui/modules/directives/modal/modal.js:10:13)
            at Object.$get.Scope.$digest (D:/work/gitrepos/angular-ui/angular-ui/test/lib/angular-1.0.1/angular.js:7661:27)
            at Object.$get.Scope.$apply (D:/work/gitrepos/angular-ui/angular-ui/test/lib/angular-1.0.1/angular.js:7855:24)
            at scope.$apply.scope.modalShown (D:/work/gitrepos/angular-ui/angular-ui/modules/directives/modal/test/modalSpec.js:20:13)

Chrome 21.0 modal model change should close modal FAILED
        TypeError: Object [object Object] has no method 'modal'
            at Object.link [as fn](D:/work/gitrepos/angular-ui/angular-ui/modules/directives/modal/modal.js:10:13)
            at Object.$get.Scope.$digest (D:/work/gitrepos/angular-ui/angular-ui/test/lib/angular-1.0.1/angular.js:7661:27)
            at Object.$get.Scope.$apply (D:/work/gitrepos/angular-ui/angular-ui/test/lib/angular-1.0.1/angular.js:7855:24)
            at null.<anonymous> (D:/work/gitrepos/angular-ui/angular-ui/modules/directives/modal/test/modalSpec.js:28:13)

Chrome 21.0 modal open/close events should set model true when modal opens FAILED
        TypeError: Object [object Object] has no method 'modal'
            at null.<anonymous> (D:/work/gitrepos/angular-ui/angular-ui/modules/directives/modal/test/modalSpec.js:38:11)

Chrome 21.0 modal open/close events should set model false when modal closes FAILED
        TypeError: Object [object Object] has no method 'modal'
            at null.<anonymous> (D:/work/gitrepos/angular-ui/angular-ui/modules/directives/modal/test/modalSpec.js:45:11) Use --force to continue. </WARN>

**Comment by pkozlowski-opensource** [comment]
OK, tests were failing since I didn't restart testacular server :-(
After the restart things are fine.

**Comment by pkozlowski-opensource** [comment]
LGTM

**Comment by dandoyon** [comment]
I've taken care of ieshiv and put in pull request

--dan

**Comment by pkozlowski-opensource** [comment]
@dandoyon : @boneskull reformatted the ieshiv in 7844b90. It is merged into master already.

**Comment by boneskull** [comment]
Guys, why is it called IE _shiv_?  A shiv is a weapon.  It seems like "shim" would be more appropriate.  Am I smoking bananas?

**Comment by dandoyon** [comment]
Yeah, well historically, I don't think shivs were used for weapons, I think this is a recent prisoner construct. As for why, I based script on something called ieshiv and didn't think to change it. How the technologists came up with both terms and both are sticking is a mystery.

**Comment by ProLoser** [comment]
I think historically... shutup.

http://code.google.com/p/html5shiv/
http://code.google.com/p/html5shim/

Also:

http://en.wikipedia.org/wiki/Shiv
http://en.wikipedia.org/wiki/Shim

**Comment by ProLoser** [comment]
P.S.
"lol that was a joke"

**Comment by dandoyon** [comment]
I stand corrected on shiv as weapon...

**Comment by ProLoser** [comment]
Just a heads up, in the future it would have been better to hold off on the conversion because now many PRs will have merge conflicts. If we had rolled out the conversion AFTER merging everything (with the next version bump) it would have been easier.

**Comment by petebacondarwin** [comment]
This is what git rebase is for.

... sent from my SAM Coupe

**Comment by petebacondarwin** [comment]
More importantly $interpolate  returns a string not a deeply nested object

Pete
...from my mobile.

**Pull request merged**
