### PR TITLE
Update ieshiv documentation

### PR DESCRIPTION
**Pull request by dandoyon**
Ieshiv issue 195

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@dandoyon @ProLoser Dan, Dean - what is is the status of this PR? There are 10 commits in in for various things so it is kind of hard to see what is going on... Among those commits there is bb54ef5 which brings boostrap things, but since now we've got a separate repo for this....

I would really like to push for a new release of angular-ui and started to look at various PRs. Would be great to have some info on this one.

**Comment by dandoyon** [comment]
Pawel, when I have time today I will review my PRs, Andy brought my initial bootstrap offerings in. I will delete this one.

I'm heading out but once back online in a couple of hours I'll re-review all your posts and put my 2 cents in.  

thanks

--dan

**Comment by dandoyon** [comment]
Pawel,

Andy cloned and pulled in the initial bootstrap stuff, I will close this PR out

Thx

Dan

**Comment by pkozlowski-opensource** [comment]
Dan, OK. And what about the IE stuff? I believe that we are still
missing sth (docs or ieshiv for JSON, don't remember exactly), no?

**Comment by dandoyon** [comment]
It has been a while, I should've put in PR much earlier.

thx

https://github.com/dandoyon/angular-ui.github.com/commit/4cddad133237c1886c1c6ffa94d9cac953515dcc

**Pull request closed without merging**
