### PR TITLE
Validate

### PR DESCRIPTION
**Pull request by ProLoser**
WIP! Do not merge yet!

Yes I know I'm doing a lot of these. I'm thinking we should use this version instead of validexp

### CODE REVIEW

**Comment by ProLoser** [comment]
For some reason `attrs.uiValidateWatch` is undefined. Any ideas? I'm guessing that either the syntax for `ui-item-whatever` doesn't work like we'd expect OR it matches `ui-validate-watch` AS `ui-validate`. Plunker will soon follow...

**Comment by ProLoser** [comment]
http://plnkr.co/edit/OZqGmo?p=preview
So first set min to 2 and max to 4. This works fine, adjusting max also works fine. However the ui-validate-watch is not being set.

If you debug inside of app.js you will see that attrs.uiValidateWatch is undefined even if the element contains the necessary attribute. Any ideas what's going on?

**Comment by petebacondarwin** [comment]
Dude!  In your html you have this:  <input name="max" type="number"
required placeholder="max" ng-model="max" ui-validate=" '$value > min' "
ui-validate-watch"'min'">
Spot the mistake?
Here's a clue - how many equals signs should there be?
I am still not happy on making people put strings around their expressions
here.  Is there some reason for changing this?
Pete

**Comment by ProLoser** [comment]
I don't like it either. It's to allow you to alternatively do " { foo:
'foo($value)', bar: 'bar($value)' } ". If you evaluate the expression
without strings, then the validation function would be executed
immediately. The strings allows me to evaluate in 2 phases. The first phase
is to store all teh validation functions, the second is to execute them
when necessary.

On Sat, Nov 3, 2012 at 1:43 AM, Pete Bacon Darwin
notifications@github.comwrote:

> Dude! In your html you have this: <input name="max" type="number"
> required placeholder="max" ng-model="max" ui-validate=" '$value > min' "
> ui-validate-watch"'min'">
> Spot the mistake?
> Here's a clue - how many equals signs should there be?
> I am still not happy on making people put strings around their expressions
> here. Is there some reason for changing this?
> Pete
> 
> On 3 November 2012 06:42, Dean Sofer notifications@github.com wrote:
> 
> > http://plnkr.co/edit/OZqGmo?p=preview
> > So first set min to 2 and max to 4. This works fine, adjusting max also
> > works fine. However the ui-validate-watch is not being set.
> > 
> > If you debug inside of app.js you will see that attrs.uiValidateWatch is
> > undefined even if the element contains the necessary attribute. Any
> > ideas
> > what's going on?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/pull/198#issuecomment-10036891>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/pull/198#issuecomment-10037465.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by ProLoser** [comment]
PS: In my plunker the watch is " ' max ' " and it seems to still be broken

On Sat, Nov 3, 2012 at 1:47 AM, Dean Sofer deansofer@gmail.com wrote:

> I don't like it either. It's to allow you to alternatively do " { foo:
> 'foo($value)', bar: 'bar($value)' } ". If you evaluate the expression
> without strings, then the validation function would be executed
> immediately. The strings allows me to evaluate in 2 phases. The first phase
> is to store all teh validation functions, the second is to execute them
> when necessary.
> 
> On Sat, Nov 3, 2012 at 1:43 AM, Pete Bacon Darwin <
> notifications@github.com> wrote:
> 
> > Dude! In your html you have this: <input name="max" type="number"
> > required placeholder="max" ng-model="max" ui-validate=" '$value > min' "
> > ui-validate-watch"'min'">
> > Spot the mistake?
> > Here's a clue - how many equals signs should there be?
> > I am still not happy on making people put strings around their
> > expressions
> > here. Is there some reason for changing this?
> > Pete
> > 
> > On 3 November 2012 06:42, Dean Sofer notifications@github.com wrote:
> > 
> > > http://plnkr.co/edit/OZqGmo?p=preview
> > > So first set min to 2 and max to 4. This works fine, adjusting max also
> > > works fine. However the ui-validate-watch is not being set.
> > > 
> > > If you debug inside of app.js you will see that attrs.uiValidateWatch
> > > is
> > > undefined even if the element contains the necessary attribute. Any
> > > ideas
> > > what's going on?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/angular-ui/angular-ui/pull/198#issuecomment-10036891>.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/pull/198#issuecomment-10037465.
> 
> ## 
> 
> Dean J Sofer
> DeanSofer@gmail.com
> 
> BS Computer Information Systems
> California State Polytechnic University, Pomona
> Telephone: 714-900-2254
> Website: www.DeanSofer.com
> Github: github.com/ProLoser

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by petebacondarwin** [comment]
I think we could do something clever with regular expressions:
- Check if the value of the attribute is wrapped in { } - in which case we
  manually parse out the key and expressions
- Otherwise assume it is a straight expression

Then you could have things like this:

ui-validate = "{ key1: myFn($value), key2: myFn2($value) }"

and

ui-validate = "myFn($value)"

without the need for all these extra strings.  This is basically what
things like ng-repeat and ng-options are doing.

Pete

**Comment by ProLoser** [comment]
Touche. Just keep in mind that with strings you're also capable of doing `{
min: '$value > min', max: '$value < max' }` or `myValidator({ value:
$value, items: [] })`

Not saying it's impossible to REGEX, I just figured it was safer not to go
crazy bothering with it. I'm still open to REGEX if I can get some help.

At this moment, I have one weird bug. If 2 inputs have the same validator,
then for some reason the validator is setting the values on both of them,
even though the models are different.

**Comment by ProLoser** [comment]
Correction, this was a bug on my part. I had 2 inputs with the same model. I just identified a strange behavior with angularjs validation. So all that's left is fleshing out the demo and the unit tests.

**Comment by ProLoser** [comment]
Can anyone help me with these unit tests? I'm not sure about how to go about doing em. If you even comment on the commits I can make the changes myself.

**Comment by ProLoser** [comment]
FINALLY ready for review/merging. Can someone give me the OK to merge this?

**Comment by ProLoser** [comment]
@joseym can you review this PR for me?

**Comment by joseym** [comment]
@ProLoser Sorry, spent the last few days handling a data disaster... I'm good now

**Comment by ProLoser** [comment]
@joseym HE LIVES!!!

**Comment by joseym** [comment]
I'm not sure I'd go that far but I am here!

**Pull request merged**
