### PR TITLE
adds a ellipsize filter

### PR DESCRIPTION
**Pull request by alexfigueiredo**
this is borrowed from codeigniter's helpers. I found it useful, maybe it
can help others.

### CODE REVIEW

**Comment by alexfigueiredo** [comment]
I'm sorry, forgot to jslint my code. Closing to do it again.

**Comment by ProLoser** [comment]
Are you aware you can do this entirely in css?

**Comment by damrbaby** [comment]
Actually you cannot do this purely in CSS if the text spans multiple lines... see http://stackoverflow.com/questions/5269713/css-ellipsis-on-second-line

**Comment by alexfigueiredo** [comment]
Also, css allow you to add the ellipsize only to the end of the string.

This filter allow you to do this:

"This is a very lon...string!"

**Comment by ProLoser** [comment]
@alexxfsilva I'm going to close this here, can you instead relocate this to @angular-ui/ui-utils ?

Also, I would try to shave the length of the filter name as much as possible (even `ellipsis`), but that's just me.

You also need tests for all the variations of ways you can call this filter.

And finally, I would like to see it pass-thru gracefully when the length property is falsy, this way someone can easily toggle the ellipsis on and off instead of having 2 DOM elements they must hide and show.

**Pull request closed without merging**
