### PR TITLE
Fixes for the issue 152

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Did my best to fix the issue #152. There are several changes in this PR:
- conversion of this directive to JavaScript (removed coffee files)
- removed isolated scope
- changed the way validity of the mask is calculated
- added (some) tests

This directive is still missing tests for making sure that model gets updated in response to DOM changes but I guess this can be covered in a separate issue.

### CODE REVIEW

**Comment by boneskull** [comment]
Chrome 19.0 uiMask ui changes on model changes should update ui valid model value FAILED
    Expected '' to be '(1)2'.
    Error: Expected '' to be '(1)2'.
        at [object Object].<anonymous> (/Volumes/projects/angular-ui/modules/directives/mask/test/maskSpec.js:21:29)

Chrome 19.0 uiMask ui changes on model changes should wipe out ui on invalid model value FAILED
    Expected '' to be '(1)2'.
    Error: Expected '' to be '(1)2'.
        at [object Object].<anonymous> (/Volumes/projects/angular-ui/modules/directives/mask/test/maskSpec.js:27:29)

**Comment by boneskull** [comment]
WHAT THE HELL IS GOING ON HERE:

[chiller@overthruster angular-ui]$ grunt test
Running "test" task
...
Chrome 19.0: Executed 3 of 136 (skipped 133) SUCCESS (0.488 / 0.043 secs)

Done, without errors.
[chiller@overthruster angular-ui]$ grunt test
Running "test" task
<WARN> Make sure the testacular server is online: run `grunt server`.
Also make sure you have a browser open to http://localhost:8080/.
............
Chrome 19.0 uiMask ui changes on model changes should update ui valid model value FAILED
    Expected '' to be '(1)2'.
    Error: Expected '' to be '(1)2'.
        at [object Object].<anonymous> (/Volumes/projects/angular-ui/modules/directives/mask/test/maskSpec.js:21:29)

Chrome 19.0 uiMask ui changes on model changes should wipe out ui on invalid model value FAILED
    Expected '' to be '(1)2'.
    Error: Expected '' to be '(1)2'.
        at [object Object].<anonymous> (/Volumes/projects/angular-ui/modules/directives/mask/test/maskSpec.js:27:29)
............................
Chrome 19.0 uiDate should retain timezone information FAILED
    Expected '2012-08-16' to equal '2012-08-17'.
    Error: Expected '2012-08-16' to equal '2012-08-17'.
        at /Volumes/projects/angular-ui/modules/directives/date/test/dateSpec.coffee.js:59:83
        at Object.invoke (/Volumes/projects/angular-ui/test/lib/angular-1.0.1/angular.js:2795:28)
        at workFn (/Volumes/projects/angular-ui/test/lib/angular-1.0.1/angular-mocks.js:1711:20)
        at /Volumes/projects/angular-ui/test/lib/angular-1.0.1/angular-mocks.js:1698:30
        at [object Object].<anonymous> (/Volumes/projects/angular-ui/modules/directives/date/test/dateSpec.coffee.js:52:12)
................................................................................
.............
Chrome 19.0: Executed 136 of 136 (3 FAILED) (1.403 / 0.957 secs) Use --force to continue. </WARN>

Aborted due to warnings.
[chiller@overthruster angular-ui]$ grunt test
Running "test" task
<WARN> Make sure the testacular server is online: run `grunt server`.
Also make sure you have a browser open to http://localhost:8080/.

Chrome 19.0 uiMask ui changes on model changes should update ui valid model value FAILED
    Expected '' to be '(1)2'.
    Error: Expected '' to be '(1)2'.
        at [object Object].<anonymous> (/Volumes/projects/angular-ui/modules/directives/mask/test/maskSpec.js:21:29)

Chrome 19.0 uiMask ui changes on model changes should wipe out ui on invalid model value FAILED
    Expected '' to be '(1)2'.
    Error: Expected '' to be '(1)2'.
        at [object Object].<anonymous> (/Volumes/projects/angular-ui/modules/directives/mask/test/maskSpec.js:27:29)

Chrome 19.0 uiDate should retain timezone information FAILED
    Expected '2012-08-16' to equal '2012-08-17'.
    Error: Expected '2012-08-16' to equal '2012-08-17'.
        at /Volumes/projects/angular-ui/modules/directives/date/test/dateSpec.coffee.js:59:83
        at Object.invoke (/Volumes/projects/angular-ui/test/lib/angular-1.0.1/angular.js:2795:28)
        at workFn (/Volumes/projects/angular-ui/test/lib/angular-1.0.1/angular-mocks.js:1711:20)
        at /Volumes/projects/angular-ui/test/lib/angular-1.0.1/angular-mocks.js:1698:30
        at [object Object].<anonymous> (/Volumes/projects/angular-ui/modules/directives/date/test/dateSpec.coffee.js:52:12)

Chrome 19.0: Executed 3 of 136 (3 FAILED) (skipped 133) (0.448 / 0.049 secs) Use --force to continue. </WARN>

Aborted due to warnings.
[chiller@overthruster angular-ui]$ grunt test
Running "test" task
...
Chrome 19.0: Executed 3 of 136 (skipped 133) SUCCESS (0.468 / 0.028 secs)

Done, without errors.

**Comment by petebacondarwin** [comment]
Do you mean why is it skipping Files?
I think testacular tries to guess what tests have changed. Generally I just
run test twice to make sure after I have changed a file.
Pete

... sent from my tablet

**Comment by petebacondarwin** [comment]
We need to completely rewrite this directive in pure js/angular since the jquery plugin is not supported and unreliable. In the meantime if it appears to work in practise let's push it out as that has got to be better than what is released right now.

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin, thnx for suggesting rewrite of this directive in pure JS / angular. +100 for this. I was seriously shocked by low quality of this jQuery directive, spent fair amount of time trying to grok it / make it work (more or less). But honestly, with the dead repo (last commit > 1 year ago), partial docs and no way of validating mask without keypress I would be all for not relaying on it.

**Comment by petebacondarwin** [comment]
On my list for Sept
... sent from my tablet

**Comment by pkozlowski-opensource** [comment]
I don't understand what is going on with those tests, for me they are passing systematically on Chrome 21/23, FFox12, IE9. @boneskull, could you try to see what is going on on Chrome 19? If those tests are unreliable we will need to change them...

**Comment by ProLoser** [comment]
Are there any active forks?

**Comment by pkozlowski-opensource** [comment]
OK, on my side I've triple-checked everything and the directive seems to be working fine, tests are passing in multiple browsers. I guess I've reached the point where someone else needs to look at this directive / tests to confirm issues seen by @boneskull. Looking into this directive today once again I'm more and more convinced that we need to rewrite it. It is not a big directive so code wouldn't be huge and it could make sane use of key events (as of today it is quite bad and we are lucky that we can cut-in with the keyup event...).

**Comment by Hoverbear** [comment]
There is a different version of the same thing here: https://github.com/RobinHerbots/jquery.inputmask#readme

It might be cleaner?

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin Peter, did you have a chance to look into this PR? What are you plans regarding the mask rewrite? Are we going to merge this one or abandon it and go with a complete rewrite?

**Comment by petebacondarwin** [comment]
I would like to do a rewrite, for a variety of reasons, but it is not at
the top of the backlog yet.

Pete
...from my mobile.

**Comment by pkozlowski-opensource** [comment]
If there are no objections I'm going to merge this one. @petebacondarwin, could you do a quick review?

**Comment by petebacondarwin** [comment]
All is good but dependencies.json is referencing the wrong mask jquery
plugin.  It should be the version that is in the test lib folder.

**Pull request merged**
