### PR TITLE
Fix synchronization between sorted list and model

### PR DESCRIPTION
**Pull request by skahlert**
I'm not sure what's the reasoning behind those two lines, but removing them seems to fix Issue #433.

### CODE REVIEW

**Comment by ProLoser** [comment]
Need testing and some more information as to why this fixes it. Any plunkers?

**Comment by skahlert** [comment]
Well, here's one:
http://embed.plnkr.co/ldSAFqHq4Gdbsvb24n2i
But behavior is the same on the demo page (see: https://github.com/angular-ui/angular-ui.github.com/issues/56)
Refresh each time:
- drag Barney to top position -> model updated correctly
- drag Anna to second position -> Anna in model stays in top position
- drag Anna to third position -> Anna in model moves to second position

Its almost like the lines were put there to create exactly that behavior, but it isn't quite how you'd expect it to behave.

Here's one with the fix:
http://embed.plnkr.co/A26vnnQi6wd1uzXJ7JLx

**Comment by ProLoser** [comment]
Can you compare your version against #394

**Comment by ProLoser** [comment]
If you test all the behaviors he mentions in the beginning of the ticket and you can confirm that this version does not recreate the problems described then I will make the necessary changes.

The main concern is when you work with lists that are not connected. I figured that the specific line in question could have been a problem though.

**Comment by skahlert** [comment]
Well... Yeah... I think it works for issue #394, too.

At least with the the example containing the newer jQueryUI version.
http://plnkr.co/edit/1ybNAQ

The first example seems broken with or without the pull-request, though.

**Comment by ProLoser** [comment]
So it was a jQueryUI bug?

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by ProLoser** [comment]
Cool well can you change your PR to delete the lines instead of commenting them out?

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by skahlert** [comment]
No worries... already done.

**Pull request merged**
