### PR TITLE
Removed one-way binding

### PR DESCRIPTION
**Pull request by dandoyon**
No compelling reason to have this.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
One use case I could imagine would look like this:

```
<span ui-currency>{{someNum}}</span>
```

It is nice and clean and seems to me intuitive as to what it does.  Any thoughts?

**Comment by dandoyon** [comment]
I like it! Certainly pretty simple usage. I'll give it a go. Thanks for input.

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin, @dandoyon for me the syntax below:

```
<span ui-currency>{{someNum}}</span>
```

looks like a use-case for a filter, no?

`{{someNum | ui-currency}}`

Maybe we should have both a directive for input fields and a filter for templates? I was using this approach for some custom formatting / parsing functionality (of course reusing code when appropriate).

**Comment by petebacondarwin** [comment]
Sounds good.

Pete
...from my mobile.
On Aug 2, 2012 6:52 AM, "Pawel Kozlowski" <
reply@reply.github.com>
wrote:

**Comment by dandoyon** [comment]
Makes sense, I was thinking that <ui-curr>{{some num}}</ui-curr> would be another

**Comment by ProLoser** [comment]
So what's the conclusion on this? Should I merge it in? As pawel said, read-only seems like a filter to me.

**Comment by dandoyon** [comment]
Not sure about it brings filter because you typically manipulate values whereas this is changing element classes

Go ahead and merge.

Thx 

Dan

**Comment by ProLoser** [comment]
Ya after re-reading the earlier comments I realized you are right.

On Sat, Aug 4, 2012 at 11:19 PM, Dan Doyon <
reply@reply.github.com

> wrote:
> 
> Not sure about it brings filter because you typically manipulate values
> whereas this is changing element classes
> 
> Go ahead and merge.
> 
> Thx
> 
> Dan
> 
> Sent from my iPhone
> 
> On Aug 4, 2012, at 5:39 PM, Dean Sofer reply@reply.github.com wrote:
> 
> > So what's the conclusion on this? Should I merge it in? As pawel said,
> > read-only seems like a filter to me.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/angular-ui/angular-ui/pull/121#issuecomment-7506694
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/angular-ui/angular-ui/pull/121#issuecomment-7508020

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Pull request merged**
