### PR TITLE
Watch date options

### PR DESCRIPTION
**Pull request by petebacondarwin**
This change allows the date directive to $watch the date widget options for changes at run time.
It should fix the problem in issue #24.

### CODE REVIEW

**Comment by ProLoser** [comment]
I think you should be using attrs.$observe(), no?

**Comment by petebacondarwin** [comment]
I might be wrong but my understanding is that $observe uses $interpolate
which requires the attribute to be wrapped in {{}}. $watch uses
$eval/$parse which expect a straight expression.

**Comment by ProLoser** [comment]
Crap. Now I have to go double check all my other directives. Have I been
doing it wrong?

On Sat, Aug 18, 2012 at 11:16 PM, Pete Bacon Darwin <
notifications@github.com> wrote:

> I might be wrong but my understanding is that $observe uses $interpolate
> which requires the attribute to be wrapped in {{}}. $watch uses
> $eval/$parse which expect a straight expression.
> On Aug 19, 2012 4:23 AM, "Dean Sofer" notifications@github.com wrote:
> 
> > I think you should be using attrs.$observe(), no?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/pull/155#issuecomment-7850267>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/pull/155#issuecomment-7850864.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by pkozlowski-opensource** [comment]
yep, @petebacondarwin is right, interpolate is for values containing `{{}}`, sth that href is using for example: `src="mypath/{{foo}}/fixedpart/{{bar}}"`.

So in the end it all boils down to supporting multiple variables in an attribute vs. attribute being an expression.

**Comment by petebacondarwin** [comment]
Also $interpolate returns a string not an object

Pete
...from my mobile.

**Pull request merged**
