### PR TITLE
Add dependencies.json and dependency checking for grunt build

### PR DESCRIPTION
**Pull request by ajoslin**

### CODE REVIEW

**Comment by ajoslin** [comment]
If this looks good, I'll rebase and merge it so the commit log is pretty.

**Comment by ajoslin** [comment]
Added ui-map dependency for https://github.com/angular-ui/angular-ui/issues/390

**Comment by ProLoser** [comment]
Some of the dependencies appear to be wrong. Inflector depends on select2? And a lot of the URLs were removed?

**Comment by ajoslin** [comment]
Oh, lol. That was a test.  What URLs were removed?  I didn't implement the core dependencies (jquery-ui, jquery, bootstrap)

**Comment by ProLoser** [comment]
Calendar, CodeMirror, Date, Mask, Inflector and TinyMCE all seem to have had their dependencies changed or wiped out.

**Comment by ajoslin** [comment]
OK.  I'll review and put them back.

**Comment by joshkurz** [comment]
Is this relevant anymore now that we are relocating everything?

**Comment by ProLoser** [comment]
Closing this since it's barely relevant anymore

**Pull request closed without merging**
