### PR TITLE
ui-event & length filter changes

### PR DESCRIPTION
**Pull request by ajoslin**
Dunno how to do two seperate pull requests for each change.

**ui-event**: needed to be able to pass the $event object like the ng-event directives, so I added that and unit tests.  I was unsure how to actually programatically add a custom event object to a jquery event for the tests, so the tests for $event are lacking right now.  Can someone help with that?

**length filter**: added ability to get length of an object, and unit tests.

Look good to all?

### CODE REVIEW

**Comment by ProLoser** [comment]
Wow, it's like mind reading. Great minds think alike. 

Andy Joslin reply@reply.github.com wrote:

ui-event needed to be able to pass the $event object like the ng-event directives. Also added unit tests.

Look good to all?

You can merge this Pull Request by running:

git pull https://github.com/ajoslin/angular-ui master

Or you can view, comment on it, or merge it online at:

https://github.com/angular-ui/angular-ui/pull/55

-- Commit Summary --
- Added ability to pass $event object in ui-event and added tests

-- File Changes --

M modules/directives/event/src/event.js (12)
A modules/directives/event/test/eventSpec.js (72)

-- Patch Links --

https://github.com/angular-ui/angular-ui/pull/55.patch
https://github.com/angular-ui/angular-ui/pull/55.diff

---

Reply to this email directly or view it on GitHub:
https://github.com/angular-ui/angular-ui/pull/55

**Comment by ProLoser** [comment]
I seriously had not seen this pull request when I wrote my reply to the bug ticket. I didn't even know that the event object was passed for the by event directives. 

 as for separate pull requests I think Pete's suggestion to make a new branch is probably the best one I've seen. I started doing it myself now. He makes a good point that you can keep adding more commits to the branch while keeping all different patches separate on their own branches

**Comment by ajoslin** [comment]
I accidentally committed some extra compiled files in the last commit... how can I undo that?

**Comment by ProLoser** [comment]
If no one else has pulled from your branch then you can simply change those commits and force push to your branch. It will however rewrite your history so if someone else does have that portion of your history you will get conflicts. 

Andy Joslin reply@reply.github.com wrote:

I accidentally committed some extra generated compiled files in the last commit... how can I undo that?

---

**Comment by ProLoser** [comment]
So I just realized that this is the ui-event directive and NOT the ui-keypress directive. We should change keypress to behave identically to ui-event however.

**Pull request merged**
