### PR TITLE
getRemote directive

### PR DESCRIPTION
**Pull request by edinella**
# getRemote directive

Loads remote data in current scope.
Useful for example to load options to feed selects, from APIs.

See it in action here:
http://plnkr.co/edit/qhfaenJ4uR0ttJkdXkn2

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@edinella out of curiosity: why would you like to load data from a directive as opposed to fetching nad exposing data on a scope from a controller? Could you share a code snippet showing how it makes things nicer / better / shorter?

**Comment by edinella** [comment]
Surely, I will prepare a detailed example.
Meanwhile, have you seen it working on Plunker?
http://plnkr.co/edit/qhfaenJ4uR0ttJkdXkn2

**Comment by pkozlowski-opensource** [comment]
yeh, so the plunk, but I'm getting bad gut feeling about it... For me it looks like you are moving $http logic to a template... What should happen in case of error? As it is now it will fail silently... And what about unit-testing...

Will let others comment but I'm somehow uneasy about this one....

**Comment by petebacondarwin** [comment]
@pawel - I guess you could add attributes for success and error that
provided callback?

It is an interesting concept, but I generally do agree with Pawel, though,
I am not sure this saves much typing and in a big application one is likely
wanting to do stuff with the data when it arrives before it goes on the
scope.

Pete

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin Sure, this directive could be extended to provide callbacks and even data transformers. But IMHO it just moves code from JavaScript (where it is easy to test) to a template (where it is impossible? to test).

**Comment by edinella** [comment]
Use case: http://plnkr.co/edit/32MRXD
To test the effect of a directive on DOM and Model don't seems too dificult, please see this: https://github.com/vojtajina/ng-directive-testing/blob/start/test/tabsSpec.js

**Comment by ProLoser** [comment]
Sorry @edinella, I think the consensus is that this directive isn't appropriate for AngularUI.

However, don't let that dissuade you from submitting any other ideas you have!

**Pull request closed without merging**
