### PR TITLE
fix bug 'has no method fullCalendar'

### PR DESCRIPTION
**Pull request by jrschumacher**
added jQuery wrapper

### CODE REVIEW

**Comment by ProLoser** [comment]
Are you sure this isn't a bug with AngularJS's jqlite not returning the original object when passing a string to `.html()`? The code looks fine to me, and I confirmed it.

**Comment by jrschumacher** [comment]
oh I guess it is then, I wasn't aware of that functionality.

// edit, I see what you are saying

**Comment by ProLoser** [comment]
I haven't tested if this IS in fact a bug with AngularJS, I just confirmed that this works properly when vanilla jQuery is loaded. Feel free to add any notes you collect or open a bug on AngularJS?

**Comment by joshkurz** [comment]
Here is a link to most updated documentation for the calendar to date. I will start working on the demo for the angular-ui website. http://www.dillingermediaonline.com/atlanta-web-developer/angularjs-calendar-2261/

**Comment by jrschumacher** [comment]
@ProLoser Yes that is the issue. Apparently I am having this problem popup all over. What version of Angular did you test with?

**Comment by ProLoser** [comment]
I didn't test to confirm that Angular's version is behaving properly, I only confirmed that the jQuery behavior works with the previously existing code.

**Pull request closed without merging**
