### PR TITLE
adding some tests for CodeMirror directive

### PR DESCRIPTION
**Pull request by boneskull**
Just learning Jasmine at this point, but this covers the basic basics, basically.  Anything else I should focus on?

### CODE REVIEW

**Comment by ProLoser** [comment]
In cases where you are merging a branch that doesn't really conflict with your changes and shouldn't merit a merging commit, you should try using git rebase.

`git rebase origin/master` or whatever your remote alias for the primary fork is will simply fast-forward all the changes and put your new commits at the end of them. Usually it's not advocated to rebase commits that have been pushed to a public server, but if no one else has merged or forked your code then you could redo your commits (if you wished) and force-pushed them to github.

**Comment by ProLoser** [comment]
NOTE TO ANYONE WHO MERGES:

You can probably just cherry-pick his commit instead of merging. I will probably merge this in later today once I have a minute to review it. Spent all day working on a Select2 rewrite.

**Comment by petebacondarwin** [comment]
This looks good.  Thanks Christopher.

On 18 July 2012 10:00, Christopher Hiller <
reply@reply.github.com

**Comment by boneskull** [comment]
Next pull request I'll try this rebasing thing.  Thanks for being patient while I am still a git noob.

**Comment by ProLoser** [comment]
I went ahead and cherry-picked the actual changing commit into master.

@boneskull I recommend executing `git reset --hard 82b731a4030373e7ff4be11166e159924060fd56` on your repo (assuming you have no local changes or other commits).  Then pull the latest from angular-ui/master. You should be able to fast forward from that ^ commit without any merging, and your tests will be in your fork. This will allow you to continue working with an identical history.

This is me being OCD about git history, so I apologize for that.

**Pull request closed without merging**
