### PR TITLE
Fixed to issue #325

### PR DESCRIPTION
**Pull request by jaroslawZawila**
Hello, 
I have experienced the same problem like the one in issue #325. This is my fix to it.

### CODE REVIEW

**Comment by ProLoser** [comment]
You only modified the build file when you are supposed to modify the source file and not commit the build files.

**Comment by jaroslawZawila** [comment]
Cool, I did it because I could not find a source file. Maybe is a stupid question but where could I find sources ??

**Comment by petebacondarwin** [comment]
https://github.com/angular-ui/angular-ui/tree/master/modules/directives/sortable

**Comment by jaroslawZawila** [comment]
Hey, I have done it in correct way this time I hope so :)

**Comment by ProLoser** [comment]
I'll merge this in on my next opportunity, but if you can, can you remove your changes to the build file? Just the Coffee file. And if possible, it would help if you can add some tests.

After this merge I will be changing the code from COFFEE to JS to keep the entire project consistent.

**Comment by jaroslawZawila** [comment]
I removed changes to build file and working on the test right now but it could take some time to accomplish it.

**Comment by martin-wintz** [comment]
Hmm, well, I'm new to Github and Angular and I was looking forward to making my first contribution. I guess I now know to make a pull request and not submit an issue if I find the solution to a problem.

**Comment by ProLoser** [comment]
@maybiusstrip

Feel free to do both :)

A pull request is also an issue:
`https://github.com/angular-ui/angular-ui/pull/340`
`https://github.com/angular-ui/angular-ui/issues/340`

But if you want you can reference an existing issue by just entering #340 in your commit or description and Github will autolink.

**Pull request merged**
