### PR TITLE
Started rewriting keypress directive

### LINKED ISSUE #154: ui-keypress needs to be refactored
ui-keypress now passes the $event object just like uiEvent does, however I ran into a few problems when working with the demo:
1. The event is binded to keydown. It is impossible to preventDefault() with the intended effect on this event.
2. It is impossible to handle multiple keys simultaneously in keypress, keydown must be used.

For this reason I think we should add 2 more variations to this directive:

ui-keypress, for common behavior, but only support a single key
ui-keydown, for multiple key behavior
ui-keyup, for any other cases

We can keep all 3 cases in the same file as different directives since they are slow closely related. It would also be ideal to get as much DRY reuse as possible out of the code.
## Related Discussions:
- https://groups.google.com/forum/?fromgroups#!searchin/angular-ui/keypress/angular-ui/RLFSPb6Vtsg/2RdDHks9kWkJ%5B1-25%5D
- https://groups.google.com/forum/?fromgroups#!searchin/angular-ui/keypress/angular-ui/bI6MLOGm_NQ/0DMuxX2rRu8J%5B1-25%5D

### PR DESCRIPTION
**Pull request by ProLoser**
Opening this PR for review. It fixes #154

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@ProLoser I've just pushed d0bd0c12a9 to the keypress branch with various fixes (code and tests). Tests are passing now, we could refactor them to remove code duplication, but this can wait. Otherwise LGTM, much cleaner than before. Would be good if someone else have a look as well.

**Comment by pkozlowski-opensource** [comment]
Guys, anyone had a second look at this one? For me it looks really good now, would be in favor of merging this one and pushing a new release. If there are no objections I will merge this one later today.

**Comment by bfricka** [comment]
Status? Jump bumping, b/c I was planning to look at this.

**Comment by ProLoser** [comment]
@brian-frichette you are the deciding factor. Checkout the branch, give it a whirl and your seal of approval and we shall do as thoust decree-eth.

**Comment by ProLoser** [comment]
My OCD just went nuts and this popped out at me:

```
link: function (scope, elm, attrs) {
      keypressHelper('keydown', scope, elm, attrs);
}
```

could be

```
link: keypressHelper('keydown')
```

Yes? No? Am I just being a mad scientist? It would require wrapping the entire return function in another function.

**Comment by bfricka** [comment]
I'll check this out when I get home tonight.  Thanks

**Comment by pkozlowski-opensource** [comment]
@brian-frichette I was looking at this PR and it was fine for me so please let us know if you hit any roadblocks!

**Comment by bfricka** [comment]
Okay, so I did some testing on this and everything works great with the hash syntax described in the docs.  I ran through a number of manual tests and it appears solid.  I originally wanted to jump in on this, b/c the demo on the docs page doesn't work.  That being said, much of what exists on that page doesn't work and it in general needs some serious TLC.  I'd be up for connecting all that stuff up and documenting it more thoroughly.

The only thing I could mention about the keypress directive: I like the optional string syntax, although apparently I'm too dense to read the docs at the top b/c I had to figure it out by deciphering what the fns were expecting based on the regex splits. _facepalm_  Either way, I like it and it should be documented.

**Comment by bfricka** [comment]
One more thing I noticed... The keypress directive noted in #154 is significantly different from this stripped down version.  At first glance, that previous one is a service that works to as a delegation point for the uiKey\* directives.  I haven't followed this for long, but I'm wondering if there are broader implications with replacing that service-oriented version (and thus removing uiKeyup and uiKeydown).

**Comment by ProLoser** [comment]
@brian-frichette you now have me really confused. When we asked you to test we were referring to the open pull request branch. The bug you mentioned has nothing to do with this issue. This version of the key press directive contains a service and all 3 variance. Now I'm not exactly sure which version you were testing. I also removed the string syntax. The person who added it was the only 1 who advocated it. It does not really coincide with any known convention. The version we should confirm is working contains the keypress ki up and key down directives.

**Comment by bfricka** [comment]
Look, I apologize. I'm new to OS collaboration. I was fairly confident that I had pulled down the correct branch, but clearly I was mistaken.  I'll revisit this when I get home and test the correct components.

**Comment by ProLoser** [comment]
No worries dude, I wasn't trying to reprimand you. I'll merge this in after some basic testing this weekend.

**Pull request merged**
