### PR TITLE
Made Calendar Watch Event Length

### PR DESCRIPTION
**Pull request by joshkurz**
The Calendar needs to watch the length of the events to ensure the best performance at the moment. We still need to find a way to watch the entire event object for alterations. This way if a title is altered then the calendar will update automatically. 

I re-wrote all of the tests to actually watch the event objects inside the calendar object. We were just testing the scope objects, which really does no good. 

Also took out some ambiguous code and edited the comments. I bumped the version to  0.3.2 and tagged the initial commit. I think the versions are behind on the build file or ahead in the package.json file. Not sure which one. 

Here is a demo link
http://www.dillingermediaonline.com/atlanta-web-developer/angularjs-calendar-2261/

### CODE REVIEW

**Comment by ProLoser** [comment]
Because our current process kind of sucks, you need to avoid committing the build files.

**Comment by joshkurz** [comment]
Ok. It built on its own so I figured it was supposed to go with the commit. So I should rebase and do it again?

**Comment by ProLoser** [comment]
Uh ya honestly I'm not sure of the _best_ way to fix things like this lol

On Fri, Nov 16, 2012 at 1:03 PM, Josh Kurz notifications@github.com wrote:

> Ok. It built on its own so I figured it was supposed to go with the
> commit. So I should rebase and do it again?
> 
> Sent from my iPhone
> 
> On Nov 16, 2012, at 3:16 PM, Dean Sofer notifications@github.com wrote:
> 
> > Because our current process kind of sucks, you need to avoid committing
> > the build files.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/pull/265#issuecomment-10462051.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by joshkurz** [comment]
Ok I'll figure it out. We should to get this in the repo soon though. It's a much better version than the current one.

**Comment by joshkurz** [comment]
Ok so I used git checkout to set a new branch. Reverted the commits and then rebased the two together.

**Pull request merged**
