### PR TITLE
New code editor : ACE

### PR DESCRIPTION
**Pull request by douglasduteil**
Hi.

He is my [ACE](http://ace.ajax.org/) directive for AngularUI.

I drop my last implementation : 

``` html
<ui-ace mode="css " onchange="changeInfo" show-gutter use-wrap-mode  ng-model="input"></ui-ace>
```

for a more common way :

``` html
<div ui-ace="{mode:'css', onChange: changeInfo, showGutter:true, useWrapMode:true}" ng-model="input" ></div>
```

### CODE REVIEW

**Comment by brianhiss** [comment]
Have you been able to get around the errors?

Could not load worker ace.js:1
{message: "SECURITY_ERR: DOM Exception 18", name: "SECURITY_ERR", code: 18, stack: "Error: An attempt was made to break through the se…cloudfront.net/src-min-noconflict/ace.js:1:76296)", INDEX_SIZE_ERR: 1…}

**Comment by douglasduteil** [comment]
Nope, this error: "An attempt was made to break through the security policy of the user agent."
come from [the creation of a worker with a distante url in ace.js](https://github.com/ajaxorg/ace-builds/blob/master/src/ace.js#L14048).
It's a « same origin restrictions »  problem. I guess it could be fixed on local projects [using ace.config.set("workerPath", "path/to/ace/src-min")](https://groups.google.com/d/msg/ace-discuss/oG0eenv3FbA/WWVOt0ka6CsJ) (not tested)

**Comment by ProLoser** [comment]
@douglasduteil https://github.com/angular-ui/ui-ace

**Comment by ProLoser** [comment]
I pushed an initial version of this code to angular-ui/ui-ace but it needs to be cleaned up a bit.

**Comment by douglasduteil** [comment]
OK @ProLoser I did it, and I registered _angular-ui-ace_ (and _angular-ui-codemirror_) on [Bower](http://sindresorhus.com/bower-components/).

**Comment by ProLoser** [comment]
Cool thanks

**Pull request closed without merging**
