### PR TITLE
Handle invalid masked setups more gracefully.

### PR DESCRIPTION
**Pull request by sja**
If there was a setup problem, i.e. you have <input ui-mask="99">, maskedinput stops here, because input.data($.mask.dataName) is undefined.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Hi @sja - Thanks for the PR.  In what situation does this occur?  I would have thought that if the mask does not initialize properly then that is a programming error that should not be hidden in a console message.

**Comment by sja** [comment]
Well, you're right, thats a programming error. I see three solutions:
1. Just leave a comment with a hint and try to call this undefined.
2. Do not call undefined and just return. This results is that only nothing happens. A programmer have to step through this (from his perspective) external code.
3. Do a console.error to force the programmer to see this point in code and immediately know what to do.

What do you prefer? Every solution has it's pros and cons.

Sebastian

Am 21.01.2013 um 14:52 schrieb Pete Bacon Darwin notifications@github.com:

**Comment by petebacondarwin** [comment]
Or throw an exception with a useful message?

```
  var maskFn = input.data($.mask.dataName);
  if (typeof maskFn !== 'function') {
    throw new Error('The Mask widget is not correctly set up');
  }
  return maskFn();
```

**Comment by sja** [comment]
You're right, that would be the best. Please see the new PR: https://github.com/angular-ui/angular-ui/pull/370

**Comment by pkozlowski-opensource** [comment]
+1 for throwing an error. Log in the console could go unnoticed.

**Pull request closed without merging**
